export default {
    REPLACE_USER_INFO: 'REPLACE_USER_INFO',
    CLEAR_USER_INFO: 'CLEAR_USER_INFO',
    HOME_INIT: 'HOME_INIT',
    MEMBER_INIT: 'MEMBER_INIT',
    CATS_INIT: 'CATS_INIT',
    CATS_PAGE: 'CATS_PAGE',
    PDETAIL_INIT: 'PDETAIL_INIT',
    EDITE_PRODUCT_ITEM: 'EDITE_PRODUCT_ITEM',
    SUBMIT_PRODUCT_ITEM: 'SUBMIT_PRODUCT_ITEM',
};
