export default {
    REPLACE_USER_INFO: 'REPLACE_USER_INFO',
    CLEAR_USER_INFO: 'CLEAR_USER_INFO',
    PDETAIL_INIT: 'PDETAIL_INIT',
    EDITE_PRODUCT_ITEM: 'EDITE_PRODUCT_ITEM',
    SUBMIT_PRODUCT_ITEM: 'SUBMIT_PRODUCT_ITEM',
};
