export default {
    PDETAIL_INIT: 'PDETAIL_INIT',
    EDITE_PRODUCT_ITEM: 'EDITE_PRODUCT_ITEM',
    SUBMIT_PRODUCT_ITEM: 'SUBMIT_PRODUCT_ITEM',
    CHOOSE_ATTR: 'CHOOSE_ATTR',
    ATTR_VALUE: 'ATTR_VALUE',
    UPLOAD_LOGO: 'UPLOAD_LOGO',
    SUBMIT_PRODUCT_DETAIL: 'SUBMIT_PRODUCT_DETAIL',
    IS_ON_SALE: 'IS_ON_SALE',
    EDIT_PRO_DESC: 'EDIT_PRO_DESC',
};
